spring:
  application:
    name: to-do-list
  datasource:
    url: jdbc:postgresql://localhost:5432/todolistproject
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
